# Site settings
author: Seyma Tas
title: Data Science Insights
header-img: img/home-bg.png
email: seymatas@gmail.com
copyright_name: Seyma Tas
description: > # this means to ignore newlines until "baseurl:"
  Just some observations
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  seyma-tas

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
